"""Add enabled_idx and disabled_idx partial indices to workflow table args

Revision ID: 9a18fa4a434f
Revises: aa298549a3cd
Create Date: 2021-05-04 11:26:01.557008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a18fa4a434f'
down_revision = 'aa298549a3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('disabled_idx', 'workflows', ['enabled'], unique=False, postgresql_where=sa.text('NOT enabled'))
    op.create_index('enabled_idx', 'workflows', ['enabled'], unique=False, postgresql_where=sa.text('enabled'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('enabled_idx', table_name='workflows')
    op.drop_index('disabled_idx', table_name='workflows')
    # ### end Alembic commands ###
