name: Snyk CI test
on:
  push:
    branches:
      - imagescan
jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    #- name: requirements
    #  run: |
    #    pip3 install -r requirements.txt

    - name: Login Docker
      env:
        PAT: ${{ secrets.G_TOKEN }}
        USERNAME: ${{ secrets.G_USERNAME }}
      run: echo $PAT | docker login ghcr.io -u $USERNAME --password-stdin
    
    - name: Build and Tag Docker Image
      run: |
        D_IMAGE=ghcr.io/vinothorg01/dimage-testing >> $GITHUB_ENV
        D_IMAGE_TAG=$D_IMAGE:latest >> $GITHUB_ENV
        docker build -t $D_IMAGE_TAG .
        docker image ls
        docker push $D_IMAGE --all-tags

    - name: Run Snyk to check code vulnerabilities
      uses: snyk/actions/python-3.8@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        #args: --sarif-file-output=snyk.sarif
        command: monitor

    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          #REGISTRY: ghcr.io
          image: ghcr.io/vinothorg01/dimage-testing
          args: --file=Dockerfile
          command: monitor