name: Snyk CI test
on: workflow_dispatch
jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      #- name: requirements
      #  run: |
      #    pip3 install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          #args: --sarif-file-output=snyk.sarif
          command: monitor

      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: snyk.sarif