##sonarcloud action
name: sonarcloud
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feature1
jobs:
  CI-Module:
    name: CI-Module
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: docker-compose build spire
        
      - name: Run Test and Coverage
        run: docker-compose run spire coverage run --source spire --omit opt/* -m pytest tests