name: Trivy Scan
on:
  push:
    branches:
      - imagescan
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login Docker
      env:
        PAT: ${{ secrets.G_TOKEN }}
        USERNAME: ${{ secrets.G_USERNAME }}
      run: echo $PAT | docker login ghcr.io -u $USERNAME --password-stdin

    - name: Build and Tag Docker Image
      run: |
        D_IMAGE=ghcr.io/vinothorg01/dimage-testing >> $GITHUB_ENV
        D_IMAGE_TAG=$D_IMAGE:latest >> $GITHUB_ENV
        docker build -t $D_IMAGE_TAG .
        docker push $D_IMAGE --all-tags

    #- name: Run Trivy vulnerability scanner
    #  uses: aquasecurity/trivy-action@master
    #  with:
    #    image-ref: 'ghcr.io/vinothorg01/dimage-testing:latest'
    #    format: 'sarif'
    #    output: 'trivy-results.sarif'
#
    #- name: Upload Trivy scan results to GitHub Security tab
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: 'trivy-results.sarif'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/vinothorg01/dimage-testing:latest'
        format: 'table'
        output: 'trivy-results.txt'

    - name: view trivy result
      run: |
        cat trivy-results.txt
